// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package gui

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets/icon.png
var resourceIconPngData []byte
var resourceIconPng = &fyne.StaticResource{
	StaticName:    "assets/icon.png",
	StaticContent: resourceIconPngData,
}
